'use strict';
const LOCATIONS=['Norte Shopping','Shopping da Pedreira','Outros'];
const CATEGORIES=['Refeição','Sobremesa','Sanduíche'];
const LABEL={admin:'Administrador',operador:'Operador',financeiro:'Financeiro'};
const monthNames=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];
const money=c=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((c||0)/100);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const el=id=>document.getElementById(id);
const nfmt=c=>new Intl.NumberFormat('pt-BR').format(c||0);
const searchKey=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR');
const dateBR=s=>s?.match(/^\d{4}-\d{2}-\d{2}$/)?`${s.slice(8,10)}/${s.slice(5,7)}/${s.slice(0,4)}`:esc(s);
const inputMoney=c=>((c||0)/100).toFixed(2).replace('.',',');
function toCents(s){const x=String(s??'').trim().replace(/\s/g,'').replace(/^R\$/,'').replaceAll('.','').replace(',','.');if(!/^\d+(\.\d{1,2})?$/.test(x))return null;let v=Math.round(Number(x)*100);return Number.isSafeInteger(v)?v:null}
const option=(v,title,selected)=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(title)}</option>`;
const opts=(list,selected,blank='')=>(blank?option('',blank,selected):'')+list.map(x=>option(x,x,selected)).join('');
const field=(id,label,value='',type='text',extra='')=>`<div class="field"><label for="${id}">${esc(label)}</label><input id="${id}" type="${type}" value="${esc(value)}" ${extra}></div>`;
const button=(text,act,id='',cls='alt small')=>`<button type="button" class="btn ${cls}" data-action="${act}" ${id?`data-id="${esc(id)}"`:''}>${esc(text)}</button>`;
function clientDot(c){return c?.inadimplente?'<span class="client-dot red" title="Inadimplência"></span>':c?.notes?.trim()?'<span class="client-dot yellow" title="Observação"></span>':''}
function metric(title,value,sub=''){return `<div class="metric"><span>${esc(title)}</span><strong>${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function table(headers,body,colspan=headers.length){return `<div class="tablebox"><table class="gridtable"><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${colspan}" class="empty">Nenhum registro.</td></tr>`}</tbody></table></div>`}
let me=null,csrf='',db={clients:[],products:[],orders:[]},page='painel',period=today().slice(0,7),locationFilter='',clientSearch='',closingSearch='',draft=[],editingOrder=null,shownClient=null;
let toastTimer;
let dayFilter='', orderClientFilter='', listState={}, modalStack=[], currentModalFactory=null, restoringModal=false, formSaving=false;
const normalizeDay=(day,month)=>day&&day.startsWith(month)?day:'';
function pageSize(key){return listState[key]?.size||20}
function paginate(key,rows){const state=listState[key]||(listState[key]={number:1,size:20});state.size=([20,50,100].includes(state.size)?state.size:20);const total=Math.max(1,Math.ceil(rows.length/state.size));state.number=Math.max(1,Math.min(total,state.number));return {visible:rows.slice((state.number-1)*state.size,state.number*state.size),total:rows.length,page:state.number,pages:total}}
function resetPage(key){if(listState[key])listState[key].number=1}
function pagination(key,data){const state=listState[key];if(!state)return '';return `<div class="pagination"><span>${data.total} registro(s) · Página ${data.page} de ${data.pages}</span><div class="actions"><label>Por página <select data-page-size="${esc(key)}">${[20,50,100].map(n=>option(String(n),String(n),String(state.size))).join('')}</select></label><button type="button" data-list-page="${esc(key)}" data-to="${data.page-1}" class="btn alt small" ${data.page<=1?'disabled':''}>← Anterior</button><button type="button" data-list-page="${esc(key)}" data-to="${data.page+1}" class="btn alt small" ${data.page>=data.pages?'disabled':''}>Próxima →</button></div></div>`}
function filteredDayOrders(){return filterOrders().filter(o=>!dayFilter||o.date===dayFilter)}
function clientName(o){return db.clients.find(c=>c.id===o.clientId)?.name||o.clientName}
function canEditOrder(o){return !!o&&allowed('admin','operador','financeiro')&&orderPaid(o)===0&&!(o.payments||[]).length&&!o.paidLocked&&(me.role==='admin'||o.createdBy===me.id)}
function restoreFocus(elm){if(elm){elm.focus();elm.setSelectionRange?.(elm.value.length,elm.value.length)}}

function toast(text,error=false){let t=el('toast');t.textContent=text;t.className='visible'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.className='',5500)}
async function api(path,method='GET',body){let init={method,credentials:'same-origin',headers:{}};if(method!=='GET'){init.headers['Content-Type']='application/json';init.headers['X-CSRF-Token']=csrf;init.body=JSON.stringify(body||{})}let r;try{r=await fetch(path,init)}catch(e){throw Error('Sem conexão com o servidor. Confira sua internet e tente novamente.')}let j;try{j=await r.json()}catch(e){throw Error('Servidor retornou dados inválidos.')}if(!r.ok){if(r.status===401 && path!=='/api/login'){me=null;showLogin()}throw Error(j.error||`Falha ${r.status}`)}return j}
async function sync(){db=await api('/api/data')}
function showLogin(){el('login-screen').classList.remove('hidden');el('app').classList.add('hidden');closeModal()}
async function start(){try{let r=await api('/api/me');me=r.user;csrf=r.csrf;await sync();showApp()}catch(err){showLogin()}}
async function showApp(){el('login-screen').classList.add('hidden');el('app').classList.remove('hidden');el('user-badge').textContent=`${me.name} · ${LABEL[me.role]}`;if(me.role==='admin'||me.role==='financeiro')page='painel';else page='pedidos';render()}
function allowed(...roles){return roles.includes(me?.role)}
function navItems(){return [
 ['painel','▦ Painel',['admin','financeiro']],['pedidos','▤ Pedidos',['admin','operador','financeiro']],['clientes','♙ Clientes',['admin','operador','financeiro']],
 ['cardapio','◈ Cardápio',['admin','operador','financeiro']],['fechamento','▣ Fechamento',['admin','financeiro']],
 ['usuarios','♟ Usuários',['admin']],['auditoria','◷ Histórico',['admin']],['dados','⚙ Meus dados',['admin']],['conta','◉ Minha conta',['admin','operador','financeiro']]
 ].filter(x=>x[2].includes(me.role))}
function go(p){if(el('modal-root').querySelector('.modal-back')&&!abandonFormAllowed())return; if(el('modal-root').querySelector('.modal-back'))closeModal();if(!navItems().some(x=>x[0]===p)){toast('Acesso não autorizado.',true);return}page=p;render();window.scrollTo(0,0)}
function render(){el('nav').innerHTML=navItems().map(([id,name])=>`<button class="${id===page?'active':''}" data-nav="${id}">${esc(name)}</button>`).join('');let names={painel:['Painel de vendas','Resumo do mês selecionado.'],pedidos:['Pedidos','Registre vários itens em um único pedido.'],clientes:['Clientes','Contatos, lojas, observações e inadimplência.'],cardapio:['Cardápio','Produtos e preços atuais; pedidos anteriores preservam os preços.'],fechamento:['Fechamento por cliente','Consulte pedidos, gere extratos e registre recebimentos.'],usuarios:['Usuários e permissões','Crie contas individuais, defina funções e revogue acessos.'],auditoria:['Histórico de atividades','Registros de quem alterou informações e quando.'],dados:['Meus dados','Backup, importação e informações sobre o armazenamento.'],conta:['Minha conta','Senha e autenticação em duas etapas.']};let [title,desc]=names[page]||names.pedidos;el('page-title').textContent=title;el('page-desc').textContent=desc;el('side-version')?.replaceChildren(document.createTextNode('v8.0'));el('page-actions').replaceChildren();let fn={painel:renderPainel,pedidos:renderPedidos,clientes:renderClientes,cardapio:renderCardapio,fechamento:renderFechamento,usuarios:renderUsuarios,auditoria:renderAuditoria,dados:renderDados,conta:renderConta}[page];fn?.()}
function pageButton(title,fn){let area=el('page-actions');area.replaceChildren();let b=document.createElement('button');b.className='btn';b.textContent=title;b.onclick=fn;area.append(b)}
function modal(html, factory=null){
 const root=el('modal-root');
 if(root.firstChild && currentModalFactory && !restoringModal)modalStack.push(currentModalFactory);
 currentModalFactory=factory;
 root.innerHTML=`<div class="modal-back"><section class="modal" role="dialog" aria-modal="true">${html}</section></div>`;
 if(modalStack.length){const heading=root.querySelector('.modal-head');if(heading){let b=document.createElement('button');b.type='button';b.className='modal-back-button';b.textContent='←';b.setAttribute('aria-label','Voltar à tela anterior');b.onclick=modalBack;heading.prepend(b)}}
 root.querySelector('.modal-back').onclick=e=>{if(e.target.classList.contains('modal-back'))toast('Use Voltar ou Fechar para sair desta janela.',true)};
 root.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>requestModalClose());
 root.querySelectorAll('form').forEach(form=>{form.dataset.dirty='false';form.addEventListener('input',()=>{form.dataset.dirty='true'});form.addEventListener('change',()=>{form.dataset.dirty='true'})});
}
function head(title){return `<div class="modal-head"><h3>${esc(title)}</h3><button class="close" type="button" data-close aria-label="Fechar">×</button></div>`}
function closeModal(){el('modal-root').replaceChildren();modalStack=[];currentModalFactory=null;restoringModal=false}
function abandonFormAllowed(){return ![...el('modal-root').querySelectorAll('form')].some(form=>form.dataset.dirty==='true')||confirm('Existem alterações não salvas. Deseja descartá-las?')}
function requestModalClose(){if(abandonFormAllowed())closeModal()}
function modalBack(){if(!abandonFormAllowed())return;if(!modalStack.length){closeModal();return}const factory=modalStack.pop();restoringModal=true;try{factory()}finally{restoringModal=false}}
async function change(path,method,payload,msg='Registro salvo.'){try{let res=await api(path,method,payload);await sync();closeModal();render();toast(msg);return res}catch(e){toast(e.message,true);return null}}
function orderTotal(o){return (o.items||[]).reduce((sum,i)=>sum+i.qty*i.priceCents,0)}
function orderPaid(o){return (o.payments||[]).reduce((sum,p)=>sum+p.amountCents,0)}
function filterOrders(){return db.orders.filter(o=>o.date.startsWith(period)&&(!locationFilter||o.location===locationFilter))}
function totals(orders){let total=orders.reduce((s,o)=>s+orderTotal(o),0),paid=orders.reduce((s,o)=>s+orderPaid(o),0);return {orders:orders.length,total,paid,due:total-paid}}
function filters(withDay=false){return `<section class="card filter"><div class="field"><label>Mês / ano</label><input type="month" id="month-filter" value="${esc(period)}"></div><div class="field"><label>Local de venda</label><select id="location-filter">${opts(LOCATIONS,locationFilter,'Todos os locais')}</select></div>${withDay?`<div class="field"><label>Dia específico (opcional)</label><input type="date" id="day-filter" min="${esc(period)}-01" max="${esc(period)}-31" value="${esc(normalizeDay(dayFilter,period))}"></div>${page==='pedidos'?`<div class="field"><label>Cliente específico</label><select id="order-client-filter">${option('','Todos os clientes',orderClientFilter)}${[...db.clients].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')).map(c=>option(c.id,c.name+(c.store?' · '+c.store:''),orderClientFilter)).join('')}</select></div>`:''}`:''}<div class="actions">${button('Limpar filtros','clear-filters','','alt small')}</div></section>`}
function periodHandlers(){el('month-filter')?.addEventListener('change',e=>{period=e.target.value||today().slice(0,7);dayFilter='';resetPage('pedidos');resetPage('fechamento');render()});el('location-filter')?.addEventListener('change',e=>{locationFilter=e.target.value;resetPage('pedidos');resetPage('fechamento');render()});el('day-filter')?.addEventListener('change',e=>{dayFilter=normalizeDay(e.target.value,period);resetPage('pedidos');render()});el('order-client-filter')?.addEventListener('change',e=>{orderClientFilter=e.target.value;resetPage('pedidos');render()})}
function renderPainel(){let rows=filteredDayOrders(),t=totals(rows);let per=LOCATIONS.map(loc=>({loc,...totals(rows.filter(o=>o.location===loc))}));el('content').innerHTML=filters(true)+`<div class="metrics">${metric('Faturamento',money(t.total))}${metric('Pedidos',nfmt(t.orders))}${metric('Recebido dos pedidos',money(t.paid))}${metric('A receber',money(t.due))}</div><section class="card"><h3>Vendas por local ${dayFilter?'· '+dateBR(dayFilter):''}</h3><div class="metrics">${per.map(x=>metric(x.loc,money(x.total),`${x.orders} pedidos`)).join('')}</div></section>`;periodHandlers()}
function renderClientes(){if(allowed('admin','operador','financeiro'))pageButton('+ Cadastrar cliente · Ctrl+Alt+N',()=>openClient());let count=LOCATIONS.map(loc=>db.clients.filter(c=>c.location===loc).length);let filtered=db.clients.filter(c=>(!locationFilter||c.location===locationFilter)&&(!clientSearch||[c.name,c.phone,c.store,c.notes].some(x=>searchKey(x).includes(searchKey(clientSearch))))).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));let pg=paginate("clientes",filtered);let rows=pg.visible.map(c=>`<tr><td><strong>${clientDot(c)}${esc(c.name)}</strong></td><td>${esc(c.location)}</td><td>${esc(c.store||'—')}</td><td>${esc(c.phone||'Não informado')}</td><td>${allowed('admin','operador','financeiro')?`<div class="actions">${button('Editar','edit-client',c.id)}${allowed('admin')?button('Excluir','delete-client',c.id,'danger small'):''}</div>`:'—'}</td></tr>`).join('');el('content').innerHTML=`<div class="metrics">${LOCATIONS.map((loc,i)=>metric(loc,nfmt(count[i]))).join('')}${metric('Total de clientes',nfmt(db.clients.length))}</div><div class="card"><div class="filter" style="margin-bottom:15px"><div class="field"><label>Buscar cliente, loja ou telefone</label><input id="client-search" value="${esc(clientSearch)}" type="search" placeholder="Nome, telefone ou loja"></div><div class="field"><label>Local de venda</label><select id="client-location-filter">${opts(LOCATIONS,locationFilter,'Todos os locais')}</select></div></div><p class="tiny muted" id="client-count">Exibindo ${filtered.length} cliente(s).</p>${table(['Cliente','Local de venda','Loja','Telefone','Ação'],rows)}${pagination('clientes',pg)}</div>`;el('client-search').oninput=e=>{clientSearch=e.target.value;resetPage('clientes');renderClientes();el('client-search').focus();el('client-search').setSelectionRange(clientSearch.length,clientSearch.length)};el('client-location-filter').onchange=e=>{locationFilter=e.target.value;resetPage('clientes');renderClientes()}}
function openClient(id){if(!allowed('admin','operador','financeiro'))return;let c=db.clients.find(x=>x.id===id);modal(`${head(c?'Editar cliente':'Cadastrar cliente')}<form id="client-form"><div class="row">${field('c-name','Nome do cliente',c?.name||'','','required maxlength="100"')}<div class="field"><label>Local de venda</label><select id="c-location">${opts(LOCATIONS,c?.location||LOCATIONS[0])}</select></div></div><div class="row" style="margin-top:11px">${field('c-store','Loja',c?.store||'','','maxlength="120"')}${field('c-phone','Telefone (opcional)',c?.phone||'','tel','maxlength="32" placeholder="(21) 99999-9999" inputmode="tel"')}</div><div class="field" style="margin-top:11px"><label>Observações</label><textarea id="c-notes" maxlength="2000">${esc(c?.notes||'')}</textarea></div>${allowed('admin','financeiro')?`<label style="display:flex;align-items:center;gap:10px;margin-top:12px"><input id="c-delinquent" type="checkbox" ${c?.inadimplente?'checked':''}> Marcar inadimplência (bolinha vermelha; prioridade sobre observações)</label>`:`<p class="tiny muted">A inadimplência somente pode ser alterada pelo administrador ou financeiro.</p>`}<div class="footer-buttons"><button type="button" class="btn alt" data-close>Cancelar</button><button class="btn">Salvar</button></div></form>`);requestAnimationFrame(()=>el('c-name')?.focus());el('c-phone').onblur=()=>{let digits=el('c-phone').value.replace(/\D/g,'');if(digits.startsWith('55')&&(digits.length===12||digits.length===13))digits=digits.slice(2);if(digits.length===11)el('c-phone').value=`(${digits.slice(0,2)}) ${digits.slice(2,7)}-${digits.slice(7)}`;else if(digits.length===10)el('c-phone').value=`(${digits.slice(0,2)}) ${digits.slice(2,6)}-${digits.slice(6)}`};el('client-form').onsubmit=async e=>{e.preventDefault();let d={name:el('c-name').value,location:el('c-location').value,store:el('c-store').value,phone:el('c-phone').value,notes:el('c-notes').value,inadimplente:allowed('admin','financeiro')?el('c-delinquent').checked:false};if(!allowed('admin','financeiro')&&c)d.inadimplente=!!c.inadimplente;
const dial=d.phone.replace(/\D/g,'').replace(/^55(?=\d{10,11}$)/,'');
const oldDial=(c?.phone||'').replace(/\D/g,'').replace(/^55(?=\d{10,11}$)/,'');
const match=dial&&dial!==oldDial&&db.clients.find(x=>x.id!==c?.id&&x.phone.replace(/\D/g,'').replace(/^55(?=\d{10,11}$)/,'')===dial);
if(match){toast('Telefone já cadastrado para '+match.name+'. Verifique antes de salvar.',true);el('c-phone').focus();return}
await change(c?'/api/clients/'+encodeURIComponent(c.id):'/api/clients',c?'PATCH':'POST',d,'Cliente salvo.')}}
function renderCardapio(){if(allowed('admin'))pageButton('+ Cadastrar produto',()=>openProduct());el('content').innerHTML=`<div class="card"><p class="muted">Refeições, sobremesas e sanduíches têm preço fixo no cardápio. Adicionais são criados diretamente no pedido.</p>${table(['Produto','Categoria','Preço','Situação','Ação'],paginate('cardapio',db.products.filter(p=>!p.archived)).visible.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.category)}</td><td>${money(p.priceCents)}</td><td><span class="pill ${p.active?'ok':'due'}">${p.active?'Disponível':'Indisponível'}</span></td><td>${allowed('admin')?`<div class="actions">${button('Editar','edit-product',p.id)}${button('Excluir','delete-product',p.id,'danger small')}</div>`:'—'}</td></tr>`).join(''))}${pagination('cardapio',paginate('cardapio',db.products.filter(p=>!p.archived)))}</div>`}
function openProduct(id){if(!allowed('admin'))return;let p=db.products.find(x=>x.id===id);modal(`${head(p?'Editar produto':'Cadastrar produto')}<form id="product-form"><div class="row">${field('p-name','Nome do produto',p?.name||'','text','required maxlength="110"')}<div class="field"><label>Categoria</label><select id="p-category">${opts(CATEGORIES,p?.category||CATEGORIES[0])}</select></div></div><div class="row" style="margin-top:12px">${field('p-price','Preço (R$)',p?inputMoney(p.priceCents):'','text','required inputmode="decimal"')}<div class="field"><label>Disponibilidade</label><select id="p-active"><option value="yes" ${!p||p.active?'selected':''}>Disponível</option><option value="no" ${p&&!p.active?'selected':''}>Indisponível</option></select></div></div><div class="footer-buttons"><button type="button" class="btn alt" data-close>Cancelar</button><button class="btn">Salvar</button></div></form>`);el('product-form').onsubmit=async e=>{e.preventDefault();let price=toCents(el('p-price').value);if(price===null){toast('Informe preço válido, por exemplo: 15,99.',true);return}await change(p?'/api/products/'+encodeURIComponent(p.id):'/api/products',p?'PATCH':'POST',{name:el('p-name').value,category:el('p-category').value,priceCents:price,active:el('p-active').value==='yes'},'Produto salvo.')}}
function renderPedidos(){if(allowed('admin','operador','financeiro'))pageButton('+ Novo pedido',()=>openOrder());
 let rows=filteredDayOrders().filter(o=>!orderClientFilter||o.clientId===orderClientFilter).slice().sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));
 let pg=paginate('pedidos',rows);
 el('content').innerHTML=filters(true)+`<div class="metrics">${metric('Pedidos encontrados',nfmt(rows.length))}${metric('Total de vendas filtradas',money(totals(rows).total))}</div><div class="card">${allowed('admin','financeiro')?`<div class="actions" style="margin-bottom:14px">${button('Exportar pedidos do mês (.txt)','export-month-orders','','dark')}${button('Exportar pedidos do mês (.csv)','export-month-csv')}</div>`:''}<p class="tiny muted">A exportação considera o mês selecionado, todos os clientes e locais; não depende da página exibida.</p>${table(['Data','Cliente','Local','Responsável','Itens','Total','Ação'],pg.visible.map(o=>`<tr><td>${dateBR(o.date)}</td><td><strong>${esc(o.clientName)}</strong></td><td>${esc(o.location)}</td><td>${esc(o.createdByName||'Não identificado')}</td><td>${o.items.map(i=>`${esc(i.qty)} × ${esc(i.name)}`).join('<br>')}</td><td>${money(orderTotal(o))}</td><td>${button('Ver pedido','view-order',o.id)}</td></tr>`).join(''))}${pagination('pedidos',pg)}</div>`;periodHandlers()}
function validItemDraft(i){return i.kind==='extra'?Boolean(i.name?.trim()):Boolean(i.productId)}
function renderDraft(){let area=el('draft-items');if(!area)return;area.innerHTML=draft.map((item,idx)=>{const common=`<div class="field sml qty-field"><label>Quantidade</label><div class="qty-controls"><button type="button" class="qty-step" data-action="decrease-qty" data-id="${idx}" aria-label="Diminuir quantidade do item ${idx+1}" ${item.qty<=1?'disabled':''}>−</button><input class="qty-input" type="text" readonly value="${esc(item.qty)}" aria-label="Quantidade do item ${idx+1}"><button type="button" class="qty-step" data-action="increase-qty" data-id="${idx}" aria-label="Aumentar quantidade do item ${idx+1}" ${item.qty>=999?'disabled':''}>+</button></div></div>`;const end=`<div class="actions">${button('×','remove-item',String(idx),'danger small')}</div>`;if(item.kind==='menu'){let ps=db.products.filter(p=>p.category===item.category&&((!p.archived&&p.active)||p.id===item.productId));return `<div class="item-line"><div class="field"><label>Produto · ${esc(item.category)}</label><select data-draft="product" data-row="${idx}">${option('','Escolha um produto',item.productId)}${ps.map(p=>option(p.id,p.name,item.productId)).join('')}</select></div>${common}<div class="field"><label>Valor unitário</label><input readonly value="${item.productId?money(item.priceCents):'—'}"></div>${end}</div>`}return `<div class="item-line"><div class="field extra-name"><label>Descrição do adicional</label><input maxlength="140" data-draft="name" data-row="${idx}" value="${esc(item.name)}" placeholder="Ex.: Muçarela extra"></div>${common}<div class="field"><label>Preço unitário (R$)</label><input data-draft="price" data-row="${idx}" inputmode="decimal" value="${esc(item.priceText??inputMoney(item.priceCents))}"></div>${end}</div>`}).join('')||'<div class="soft">Adicione uma refeição, sobremesa, sanduíche ou adicional.</div>';let total=draft.reduce((sum,i)=>sum+i.qty*(i.priceCents||0),0);el('draft-total').textContent=money(total)}
function openOrder(id){if(!allowed('admin','operador','financeiro'))return;let o=db.orders.find(x=>x.id===id);if(o&&!canEditOrder(o)){toast('Pedidos com pagamentos não podem ser editados. Você só pode editar pedidos próprios sem pagamento.',true);return}editingOrder=o||null;draft=o?o.items.map(i=>({...i,priceText:inputMoney(i.priceCents)})):[];const loc=o?.location||LOCATIONS[0];modal(`${head(o?'Editar pedido':'Novo pedido')}<form id="order-form"><div class="row">${field('o-date','Data',o?.date||today(),'date','required')}<div class="field"><label>Local de venda</label><select id="o-location" ${o?'disabled':''}>${opts(LOCATIONS,loc)}</select></div><div class="field big"><label>Cliente</label><select id="o-client" ${o?'disabled':''}></select></div></div><p class="soft" id="selected-client-store" style="margin:12px 0 0">Loja do cliente: —</p><h4 style="margin:22px 0 9px">Itens do pedido</h4><div id="draft-items"></div><div class="actions" style="margin-top:11px">${CATEGORIES.map(c=>button('+ '+c,'add-menu',c,'alt small')).join('')}${button('+ Adicional','add-extra','','alt small')}</div><div class="total"><span>Total do pedido</span><strong id="draft-total">R$ 0,00</strong></div><div class="field" style="margin-top:14px"><label>Observações sobre o pedido</label><textarea id="o-notes" maxlength="600">${esc(o?.notes||'')}</textarea></div>${o?`<div class="notice" style="margin-top:14px">Recebido até agora: ${money(orderPaid(o))}. O total não pode ficar abaixo do já recebido.</div>`:''}<div class="footer-buttons"><button type="button" class="btn alt" data-close>Cancelar</button><button class="btn">Salvar pedido</button></div></form>`);let showStore=()=>{const c=db.clients.find(c=>c.id===el('o-client').value);if(el('selected-client-store'))el('selected-client-store').textContent='Loja do cliente: '+(c?.store||o?.store||'—')};
let updateCustomers=()=>{let selected=el('o-client').value||o?.clientId||'';el('o-client').innerHTML=option('','Selecione o cliente',selected)+db.clients.filter(c=>c.location===el('o-location').value).map(c=>option(c.id,c.name,selected)).join('');showStore()};
updateCustomers();el('o-client').onchange=showStore;
el('o-location').onchange=()=>{el('o-client').innerHTML=option('','Selecione o cliente','')+db.clients.filter(c=>c.location===el('o-location').value).map(c=>option(c.id,c.name,'' )).join('');showStore()};
renderDraft();el('order-form').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-draft],.qty-input'))e.preventDefault()});el('order-form').onsubmit=async e=>{e.preventDefault();let items=[];for(let i of draft){if(!Number.isInteger(i.qty)||i.qty<1||i.qty>999||!validItemDraft(i)||!Number.isInteger(i.priceCents)||i.priceCents<0){toast('Confira produto, quantidade e preço dos itens.',true);return}items.push({kind:i.kind,productId:i.kind==='menu'?i.productId:null,name:i.name,category:i.category,qty:i.qty,priceCents:i.priceCents})}if(!items.length||!el('o-client').value){toast('Selecione o cliente e pelo menos um item.',true);return}const data={date:el('o-date').value,clientId:el('o-client').value,items,notes:el('o-notes').value};if(o)data.updatedAt=o.updatedAt;
 if(formSaving)return;formSaving=true;const saveButton=el('order-form').querySelector('button[type="submit"],button:not([type])');if(saveButton)saveButton.disabled=true;
 try{if(o){await change('/api/orders/'+encodeURIComponent(o.id),'PATCH',data,'Pedido atualizado.');return}
 await api('/api/orders','POST',data);await sync();render();
 const keepDate=data.date,keepLoc=el('o-location').value;
 draft=[];el('o-client').value='';el('o-notes').value='';el('o-date').value=keepDate;el('o-location').value=keepLoc;renderDraft();showStore();el('order-form').dataset.dirty='false';el('o-client').focus();toast('Pedido salvo. Pronto para o próximo pedido.');
 }catch(err){toast(err.message,true)}finally{formSaving=false;if(saveButton?.isConnected)saveButton.disabled=false}}}
function openOrderDetail(id){let o=db.orders.find(x=>x.id===id);if(!o)return;let paid=orderPaid(o),total=orderTotal(o),due=total-paid;modal(`${head('Pedido · '+dateBR(o.date))}<p><strong>${esc(o.clientName)}</strong> · ${esc(o.location)} · ${esc(o.store||'—')}</p><p class="tiny muted">Responsável pela venda: ${esc(o.createdByName||'Não identificado')}</p>${table(['Item','Qtd.','Preço un.','Subtotal'],o.items.map(i=>`<tr><td>${esc(i.name)}<div class="tiny muted">${esc(i.category)}</div></td><td>${nfmt(i.qty)}</td><td>${money(i.priceCents)}</td><td>${money(i.qty*i.priceCents)}</td></tr>`).join(''))}<div class="total"><span>Total do pedido</span><strong>${money(total)}</strong></div>${allowed('admin','financeiro')?`<div class="soft" style="margin-top:11px">Recebido: ${money(paid)} · Saldo: ${money(due)}</div>`:''}${o.notes?`<p class="soft">${esc(o.notes)}</p>`:''}<div class="footer-buttons">${allowed('admin','financeiro')&&due>0?button('Registrar pagamento','pay-order',o.id,'alt'):''}${allowed('admin','operador','financeiro')&&canEditOrder(o)?button('Editar pedido','edit-order',o.id):''}${allowed('admin')&&paid===0?button('Excluir pedido','delete-order',o.id,'danger'):''}<button class="btn alt" data-close>Fechar</button></div>`,()=>openOrderDetail(id))}
function openPay(id){if(!allowed('admin','financeiro'))return;const o=db.orders.find(x=>x.id===id);if(!o)return;let due=orderTotal(o)-orderPaid(o);if(due<=0)return;modal(`${head('Registrar pagamento')}<p><strong>${esc(o.clientName)}</strong> · pedido ${dateBR(o.date)}</p><p>Saldo a receber: <strong>${money(due)}</strong></p><form id="pay-form"><div class="row">${field('pay-date','Data do recebimento',today(),'date','required')}${field('pay-value','Valor recebido (R$)',inputMoney(due),'text','required inputmode="decimal"')}</div><div class="footer-buttons"><button class="btn alt" data-close type="button">Cancelar</button><button class="btn">Confirmar recebimento</button></div></form>`);el('pay-form').onsubmit=async e=>{e.preventDefault();let cents=toCents(el('pay-value').value);if(!cents||cents>due){toast('Informe um valor maior que zero e até '+money(due),true);return}await change('/api/payments','POST',{orderId:o.id,date:el('pay-date').value,amountCents:cents},'Pagamento registrado.')}}
function historicalClient(cid,orders){return db.clients.find(c=>c.id===cid)||{id:cid,name:orders[0]?.clientName||'Cliente excluído',location:orders[0]?.location||'',store:orders[0]?.store||'',phone:'',notes:'',inadimplente:false,archived:true}}
function clientGroups(){let m=new Map;filterOrders().forEach(o=>{if(!m.has(o.clientId))m.set(o.clientId,[]);m.get(o.clientId).push(o)});return [...m.entries()].map(([cid,orders])=>({client:historicalClient(cid,orders),cid,orders,t:totals(orders)})).sort((a,b)=>(a.client?.name||'').localeCompare(b.client?.name||'','pt-BR'))}
function renderFechamento(){let groups=clientGroups().filter(g=>!closingSearch||searchKey(g.client?.name).includes(searchKey(closingSearch)));let pg=paginate('fechamento',groups);let t=totals(filterOrders());el('content').innerHTML=filters()+`<div class="metrics">${metric('Clientes com pedidos',nfmt(groups.length))}${metric('Pedidos',nfmt(t.orders))}${metric('Compras',money(t.total))}${metric('Saldo a receber',money(t.due))}</div><section class="card"><div class="field" style="max-width:430px;margin-bottom:15px"><label>Buscar cliente pelo nome</label><input id="closing-search" type="search" value="${esc(closingSearch)}" placeholder="Digite o nome do cliente…"></div><p class="tiny muted">${groups.length} cliente(s) no período/local selecionado.</p>${table(['Cliente','Local','Responsável','Pedidos','Total','Recebido','Saldo','Ação'],pg.visible.map(g=>`<tr class="${g.t.orders&&g.t.due===0?'row-paid':''}"><td><strong>${clientDot(g.client)}${esc(g.client?.name||'Cliente')}</strong></td><td>${esc(g.orders[0]?.location||'')}</td><td>${esc([...new Set(g.orders.map(o=>o.createdByName||'Não identificado'))].join(', '))}</td><td>${g.t.orders}</td><td>${money(g.t.total)}</td><td>${money(g.t.paid)}</td><td>${money(g.t.due)}</td><td><div class="actions">${button('Extrato','statement',g.cid)}${button('WhatsApp / texto','share',g.cid)}</div></td></tr>`).join(''))}${pagination('fechamento',pg)}</section>`;periodHandlers();el('closing-search').oninput=e=>{closingSearch=e.target.value;resetPage('fechamento');renderFechamento();restoreFocus(el('closing-search'))}}
function groupFor(cid){const orders=filterOrders().filter(o=>o.clientId===cid).sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt.localeCompare(b.createdAt));const client=orders.length?historicalClient(cid,orders):db.clients.find(c=>c.id===cid);return {client,orders,t:totals(orders)}}
function openStatement(cid){const {client,orders,t}=groupFor(cid);if(!client)return;modal(`${head('Extrato do cliente')}<p><strong>${clientDot(client)}${esc(client.name)}</strong> · ${esc(client.location)} · ${esc(period)}</p><div class="metrics">${metric('Pedidos',String(t.orders))}${metric('Total de compras',money(t.total))}${metric('Recebido',money(t.paid))}${metric('A receber',money(t.due))}</div><div class="actions" style="margin:14px 0">${button('Extrato para WhatsApp','share',cid,'alt')}${allowed('admin','financeiro')&&t.due>0?button('Quitar todos os pedidos pendentes deste mês','bulk',cid,'dark'):''}</div>${orders.map((o,i)=>`<div class="card"><div class="section-title"><h4>Pedido ${i+1} · ${dateBR(o.date)}<br><span class="tiny muted">Responsável: ${esc(o.createdByName||'Não identificado')}</span></h4><span class="pill ${orderPaid(o)<orderTotal(o)?'due':'ok'}">${orderPaid(o)>=orderTotal(o)?'Pago':orderPaid(o)>0?'Parcial':'Pendente'}</span></div>${o.items.map(item=>`<div>${nfmt(item.qty)} × ${esc(item.name)} — ${money(item.qty*item.priceCents)}</div>`).join('')}<p><strong>Total: ${money(orderTotal(o))}</strong></p>${button('Ver pedido','view-order',o.id)}</div>`).join('')}<div class="footer-buttons"><button class="btn alt" data-close>Fechar</button></div>`,()=>openStatement(cid))}
function statementText(cid){let {client,orders,t}=groupFor(cid);return statementTextFromOrders(client,orders,period)}
function statementTextFromOrders(client,orders,monthPeriod,includeHeading=true){let year=monthPeriod.slice(0,4),month=monthNames[Number(monthPeriod.slice(5,7))-1]||monthPeriod;let divider='────────────────────';let ordered=orders.slice().sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt.localeCompare(b.createdAt));let lines=includeHeading?['*SABORES DAS DIVAS*',`*Pedidos de ${month} de ${year}*`,`Cliente: ${client?.name||'Cliente'}`,divider]:[`Cliente: ${client?.name||'Cliente'}`,divider];ordered.forEach((o,index)=>{const paid=orderPaid(o),total=orderTotal(o),due=Math.max(0,total-paid);lines.push(`PEDIDO ${index+1} — ${dateBR(o.date)}`);o.items.forEach(i=>lines.push(`${i.qty} × ${i.name} — ${money(i.qty*i.priceCents)} (${money(i.priceCents)} un.)`));lines.push(`Total do pedido: ${money(total)}`);if(due===0)lines.push('Status: PAGO');else if(paid>0){lines.push(`Valor pago: ${money(paid)}`);lines.push(`Restante: ${money(due)}`)}lines.push(divider)});if(!ordered.length)lines.push('Nenhum pedido registrado neste mês.',divider);lines.push(`Quantidade de pedidos: ${ordered.length}`,`TOTAL A PAGAR: ${money(ordered.reduce((s,o)=>s+Math.max(0,orderTotal(o)-orderPaid(o)),0))}`);return lines.join('\n')}
function exportMonthlyText(){const rows=db.orders.filter(o=>o.date.startsWith(period));const m=new Map();rows.forEach(o=>{if(!m.has(o.clientId))m.set(o.clientId,[]);m.get(o.clientId).push(o)});const groups=[...m.entries()].map(([id,items])=>({client:historicalClient(id,items),items})).sort((a,b)=>a.client.name.localeCompare(b.client.name,'pt-BR'));
let text=`*SABORES DAS DIVAS*\n*RELATÓRIO GERAL — ${monthNames[Number(period.slice(5,7))-1]} DE ${period.slice(0,4)}*\n`+groups.map(({client,items})=>'-------------------------------------------------\n-------------------------------------------------\n'+statementTextFromOrders(client,items,period,false)).join('\n');if(!groups.length)text+='Nenhum pedido no período.';download('Pedidos_gerais_'+period+'.txt',text)}
function exportMonthlyCsv(){const rows=db.orders.filter(o=>o.date.startsWith(period)).sort((a,b)=>a.clientName.localeCompare(b.clientName,'pt-BR')||a.date.localeCompare(b.date));const csv=v=>'"'+String(v??'').replaceAll('"','""')+'"';let lines=[['Cliente','Local','Loja','Data','Pedido','Produto','Categoria','Quantidade','Valor unitário (R$)','Subtotal (R$)','Total pedido (R$)','Pago pedido (R$)','Saldo pedido (R$)','Responsável'].map(csv).join(';')];rows.forEach(o=>(o.items||[]).forEach((i,idx)=>lines.push([o.clientName,o.location,o.store,dateBR(o.date),o.id,i.name,i.category,i.qty,inputMoney(i.priceCents),inputMoney(i.qty*i.priceCents),idx===0?inputMoney(orderTotal(o)):'',idx===0?inputMoney(orderPaid(o)):'',idx===0?inputMoney(orderTotal(o)-orderPaid(o)):'',o.createdByName].map(csv).join(';'))));download('Pedidos_gerais_'+period+'.csv','\uFEFF'+lines.join('\r\n'),'text/csv;charset=utf-8')}
function whatsPhone(v){let d=String(v||'').replace(/\D/g,'');if(d.startsWith('55')&&(d.length===12||d.length===13))d=d.slice(2);return d.length===10||d.length===11?'55'+d:''}
function shareStatement(cid){let {client}=groupFor(cid);if(!client)return;let text=statementText(cid);let phone=whatsPhone(client.phone);modal(`${head('Extrato para WhatsApp')}<p><strong>${esc(client.name)}</strong> · ${esc(period)}</p><label>Mensagem pronta para copiar<textarea id="share-text" readonly class="statement-message">${esc(text)}</textarea></label><div class="actions" style="margin-top:12px">${button('Copiar texto','copy-share','','dark')}${button('Baixar .txt','download-share')}${phone?button('Abrir WhatsApp','open-whatsapp',phone):''}</div><p class="tiny muted">Confira o texto e o contato antes de enviar. O envio não é automático.</p>`,()=>shareStatement(cid))}
function bulkPay(cid){if(!allowed('admin','financeiro'))return;let {client,orders,t}=groupFor(cid);if(!t.due)return;let pending=orders.filter(o=>orderTotal(o)>orderPaid(o));modal(`${head('Quitar todos os pedidos pendentes')}<p><strong>${esc(client.name)}</strong> · ${esc(period)}</p><p>${pending.length} pedidos pendentes · total a receber: <strong>${money(t.due)}</strong>.</p><p>Pedidos parcialmente pagos receberão apenas o saldo restante.</p><form id="bulk-form">${field('bulk-date','Data do recebimento',today(),'date','required')}<div class="footer-buttons"><button class="btn alt" data-close type="button">Cancelar</button><button class="btn" type="submit">Confirmar quitação de ${pending.length} pedidos</button></div></form>`);el('bulk-form').onsubmit=async e=>{e.preventDefault();if(!confirm('Confirmar o recebimento total de '+money(t.due)+' referente a '+pending.length+' pedido(s)?'))return;await change('/api/payments/bulk','POST',{clientId:cid,period,date:el('bulk-date').value},'Todos os pedidos pendentes foram quitados.')}}
function renderUsuarios(){pageButton('+ Adicionar usuário',()=>openInvite());el('content').innerHTML=`<div class="notice">O nome da pessoa é também o usuário para login; o e-mail é uma alternativa de acesso. A senha provisória tem 6 dígitos e pode continuar sendo usada, sem obrigatoriedade de troca. É recomendável ativar duas etapas. Ao excluir um acesso, os pedidos e pagamentos feitos por ele permanecem registrados.</div><div class="card" id="users-table">Carregando usuários…</div>`;api('/api/users').then(r=>{el('users-table').innerHTML=table(['Nome / usuário','E-mail','Perfil','Situação','2 etapas','Ação'],paginate('usuarios',r.users).visible.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${esc(LABEL[u.role])}</td><td><span class="pill ${u.active?'ok':'due'}">${u.active?'Ativo':'Desativado'}</span></td><td>${u.totpEnabled?'Ativo':'Não'}</td><td><div class="actions">${button('Editar','edit-user',u.id)}${u.id!==me.id?button('Nova senha','reset-user',u.id):''}${u.id!==me.id?button('Excluir','delete-user',u.id,'alt small'):''}</div></td></tr>`).join(''))+pagination('usuarios',paginate('usuarios',r.users));window.__users=r.users}).catch(e=>toast(e.message,true))}
function openInvite(){modal(`${head('Adicionar usuário')}<form id="invite-form"><div class="row">${field('u-name','Nome / usuário para login','','text','required minlength="3" maxlength="100"')}${field('u-email','E-mail','','email','required maxlength="200"')}</div><div class="field" style="margin-top:12px"><label>Perfil de acesso</label><select id="u-role">${['operador','financeiro','admin'].map(r=>option(r,LABEL[r],'operador')).join('')}</select></div><p class="tiny muted">O nome informado será o mesmo exibido no sistema e utilizado no login. Também será possível entrar com o e-mail. A senha provisória terá 6 números.</p><div class="footer-buttons"><button class="btn alt" type="button" data-close>Cancelar</button><button class="btn">Adicionar usuário</button></div></form>`);el('invite-form').onsubmit=async e=>{e.preventDefault();try{let r=await api('/api/users','POST',{name:el('u-name').value,email:el('u-email').value,role:el('u-role').value});renderUsuarios();showTemporaryPassword(r.temporaryPassword,'Usuário criado.',r.username)}catch(err){toast(err.message,true)}}}
function showTemporaryPassword(pass,title,username=''){modal(`${head(title)}<div class="notice"><strong>Senha provisória de 6 números.</strong> Ela já permite acesso completo de acordo com o perfil e não precisa ser alterada. Compartilhe-a somente em canal privado; recomendamos ativar duas etapas.</div>${username?`<p>Nome de usuário: <strong>${esc(username)}</strong></p>`:''}<label>Senha provisória<input id="temporary-secret" readonly value="${esc(pass)}"></label><div class="footer-buttons">${button('Copiar senha','copy-temp','','dark')}<button class="btn alt" data-close>Fechar</button></div>`)}
function editUser(id){let u=window.__users?.find(x=>x.id===id);if(!u)return;modal(`${head('Permissões do usuário')}<p>${esc(u.email)}</p><form id="user-edit-form"><div class="field">${field('u-edit-name','Nome / usuário para login',u.name,'text','required minlength="3" maxlength="100"')}</div><div class="field" style="margin-top:12px"><label>Perfil</label><select id="u-edit-role">${['admin','operador','financeiro'].map(r=>option(r,LABEL[r],u.role)).join('')}</select></div><div class="field" style="margin-top:12px"><label>Situação</label><select id="u-edit-active"><option value="yes" ${u.active?'selected':''}>Ativo</option><option value="no" ${!u.active?'selected':''}>Desativado (revogar acesso)</option></select></div><div class="footer-buttons"><button class="btn alt" data-close type="button">Cancelar</button><button class="btn">Salvar permissões</button></div></form>`);el('user-edit-form').onsubmit=async e=>{e.preventDefault();if(!confirm('Confirmar alteração de acesso? As sessões desse usuário serão encerradas.'))return;let ok=await change('/api/users/'+encodeURIComponent(id),'PATCH',{name:el('u-edit-name').value,role:el('u-edit-role').value,active:el('u-edit-active').value==='yes'},'Permissões atualizadas.');if(ok){if(id===me.id){await start()}else renderUsuarios()}}}
async function resetUser(id){if(!confirm('Redefinir a senha deste usuário para uma nova senha provisória de 6 dígitos? As sessões atuais serão encerradas, mas ele poderá continuar usando a senha provisória sem trocá-la.'))return;try{let r=await api('/api/users/'+encodeURIComponent(id)+'/reset','POST',{});showTemporaryPassword(r.temporaryPassword,'Senha redefinida.')}catch(e){toast(e.message,true)}}
async function deleteUser(id){let u=window.__users?.find(x=>x.id===id);if(!u||id===me.id)return;let typed=prompt(`Excluir o acesso de ${u.name} (${u.email})? Os pedidos e pagamentos dele serão preservados.

Para confirmar, digite EXCLUIR:`);if(typed!=='EXCLUIR')return;try{await api('/api/users/'+encodeURIComponent(id),'DELETE',{});window.__users=window.__users.filter(x=>x.id!==id);renderUsuarios();toast('Acesso excluído. Vendas, pagamentos e histórico preservados.')}catch(e){toast(e.message,true)}}
function renderAuditoria(){el('content').innerHTML='<div class="card" id="audit-content">Carregando histórico…</div>';api('/api/audit').then(r=>{el('audit-content').innerHTML=`<p class="muted tiny">Últimos 250 eventos, armazenados no banco de dados.</p>${table(['Quando (UTC)','Responsável','Ação','Área','Identificador'],paginate('auditoria',r.events).visible.map((e)=>`<tr><td>${esc(e.at)}</td><td>${esc(e.actor_email)}</td><td>${esc(e.event.replaceAll('_',' '))}</td><td>${esc(e.object_type)}</td><td class="tiny">${esc(e.object_id)} ${button('Detalhes','audit-detail',String(r.events.indexOf(e)))}</td></tr>`).join(''))}${pagination('auditoria',paginate('auditoria',r.events))}`;window.__auditEvents=r.events}).catch(e=>toast(e.message,true))}
function renderDados(){el('content').innerHTML=`<div class="card"><h3>Armazenamento centralizado</h3><p>Os dados são mantidos no banco de dados do servidor. Não dependem do armazenamento deste navegador.</p><p><strong>${db.clients.length} clientes · ${db.products.length} produtos · ${db.orders.length} pedidos.</strong></p><div class="actions">${button('Exportar dados do negócio (.json)','export-data','','dark')}</div><p class="tiny muted">Este arquivo inclui contatos e pedidos. Guarde-o em lugar privado. Não contém senhas ou contas de acesso.</p></div><div class="card danger-zone"><h3>Migração da versão antiga</h3><p>Se você já registrou pedidos na versão HTML anterior, exporte um backup JSON daquela versão e importe aqui. A importação é permitida <strong>somente antes de criar qualquer pedido ou produto no sistema online</strong>. Ela substitui os clientes iniciais e importa os clientes, os produtos, os pedidos e os pagamentos do backup.</p><label class="btn alt file-btn">Selecionar backup antigo (.json)<input id="old-backup" type="file" accept=".json,application/json"></label></div><div class="card"><h3>Backups do servidor</h3><p>O servidor inclui uma rotina automática de cópia do banco de dados a cada 24 horas com retenção local de 30 dias quando implantado pelo arquivo Docker Compose. Também é necessário copiar os backups para outro local protegido contra perda do servidor.</p></div>`;el('old-backup').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;try{let backup=JSON.parse(await f.text());if(!confirm(`Importar o backup ${f.name}? Os clientes iniciais serão substituídos, e a importação só funciona antes de haver pedidos ou produtos neste servidor.`))return;let response=await api('/api/import','POST',backup);await sync();go('clientes');toast(`Importados ${response.clients} clientes e ${response.orders} pedidos.`)}catch(err){toast(err.message,true)}}}
function renderConta(){el('content').innerHTML=`<div class="card"><h3>Minha conta</h3><p>${esc(me.name)} · ${esc(me.email)} · ${esc(LABEL[me.role])}</p><div class="actions">${button('Alterar senha','password','','dark')}${me.totpEnabled?'<span class="pill ok">Autenticação em duas etapas ativada</span>':button('Ativar duas etapas','setup-totp')}</div></div><div class="notice">Uma senha provisória de 6 dígitos pode continuar em uso sem troca, mas é menos resistente a tentativas de acesso. Recomendamos ativar a autenticação em duas etapas. Para redefinir o segundo fator, procure o administrador.</div>`}
function openPassword(required=false){modal(`${head(required?'Troque a senha provisória':'Alterar senha')}<p>${required?'É obrigatório trocar a senha temporária antes de usar o sistema.':'Sua nova senha deve ter pelo menos 4 caracteres.'}</p><form id="pass-form">${field('old-pass','Senha atual','','password','required autocomplete="current-password"')}${field('new-pass','Nova senha (mín. 4 caracteres)','','password','required minlength="4" autocomplete="new-password"')}${field('confirm-pass','Repita a nova senha','','password','required minlength="4" autocomplete="new-password"')}<div class="footer-buttons"><button class="btn">Salvar nova senha</button></div></form>`);el('pass-form').onsubmit=async e=>{e.preventDefault();if(el('new-pass').value!==el('confirm-pass').value){toast('As senhas não coincidem.',true);return}try{await api('/api/password','POST',{oldPassword:el('old-pass').value,newPassword:el('new-pass').value});csrf='';me=null;showLogin();toast('Senha atualizada. Faça login novamente.')}catch(err){toast(err.message,true)}};if(required){el('modal-root').querySelectorAll('[data-close]').forEach(x=>x.remove());el('modal-root').querySelector('.modal-back').onclick=null}}
async function setupTotp(){try{let r=await api('/api/totp/setup','POST',{});modal(`${head('Ativar autenticação em duas etapas')}<p>No seu aplicativo autenticador (Google Authenticator, Microsoft Authenticator etc.), adicione uma conta manualmente com a chave abaixo. Depois digite o código de seis dígitos para ativar.</p><p class="badge" style="font-family:monospace">${esc(r.secret)}</p><p class="tiny muted">Guarde a chave de recuperação com segurança. Não a compartilhe nem salve em locais públicos.</p><form id="totp-form">${field('totp-code','Código de 6 dígitos','','text','required inputmode="numeric" minlength="6" maxlength="6" pattern="[0-9]{6}"')}<div class="footer-buttons"><button class="btn">Ativar</button></div></form>`);el('totp-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/totp/confirm','POST',{code:el('totp-code').value});me.totpEnabled=true;closeModal();render();toast('Autenticação em duas etapas ativada.')}catch(err){toast(err.message,true)}}}catch(e){toast(e.message,true)}}
function download(filename,text,type='text/plain;charset=utf-8'){let blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)}
function pendingModalAction(action,button){switch(action){case 'edit-client':return openClient(button.dataset.id);case 'delete-client':{
 if(!allowed('admin'))return;
 const id=button.dataset.id,c=db.clients.find(x=>x.id===id);
 if(!c)return toast('Cliente não encontrado.',true);
 if(!confirm(`Excluir o cliente “${c.name}” do cadastro?\n\nCaso existam pedidos já quitados, eles e seus pagamentos serão preservados no histórico. Clientes com pagamentos pendentes precisam ser quitados antes da exclusão.`))return;
 return change('/api/clients/'+encodeURIComponent(id),'DELETE',{},'Cliente excluído do cadastro.');}
case 'edit-product':return openProduct(button.dataset.id);case 'delete-product':{
 if(!allowed('admin'))return;
 const id=button.dataset.id,p=db.products.find(x=>x.id===id&&!x.archived);
 if(!p)return toast('Produto não encontrado.',true);
 if(!confirm(`Excluir o produto “${p.name}” do cardápio? Ele deixará de estar disponível para novos pedidos. Pedidos e extratos anteriores serão preservados.`))return;
 return change('/api/products/'+encodeURIComponent(id),'DELETE',{},'Produto excluído do cardápio.');}
case 'view-order':return openOrderDetail(button.dataset.id);case 'edit-order':return openOrder(button.dataset.id);case 'pay-order':return openPay(button.dataset.id);case 'statement':return openStatement(button.dataset.id);case 'share':return shareStatement(button.dataset.id);case 'bulk':return bulkPay(button.dataset.id);case 'edit-user':return editUser(button.dataset.id);case 'reset-user':return resetUser(button.dataset.id);case 'delete-user':return deleteUser(button.dataset.id);case 'audit-detail':{let a=window.__auditEvents?.[Number(button.dataset.id)];if(a)modal(`${head('Detalhes da alteração')}<p>${esc(a.at)} · ${esc(a.actor_email)} · ${esc(a.event)}</p><h4>Antes</h4><pre class="soft" style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(a.before_json||'—')}</pre><h4>Depois</h4><pre class="soft" style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(a.after_json||'—')}</pre>`);return}case 'password':return openPassword();case 'setup-totp':return setupTotp();case 'add-menu':{if(el('order-form'))el('order-form').dataset.dirty='true';let cat=button.dataset.id;let p=db.products.find(p=>p.category===cat&&p.active&&!p.archived);if(!p){toast('Cadastre um produto disponível de '+cat+' no cardápio.',true);return}draft.push({kind:'menu',productId:p.id,name:p.name,category:cat,qty:1,priceCents:p.priceCents});return renderDraft()}case 'add-extra':if(el('order-form'))el('order-form').dataset.dirty='true';draft.push({kind:'extra',productId:null,name:'',category:'Adicional',qty:1,priceCents:0,priceText:'0,00'});return renderDraft();case 'decrease-qty':case 'increase-qty':{
 if(el('order-form'))el('order-form').dataset.dirty='true';const idx=Number(button.dataset.id),item=draft[idx];if(!item)return;
 item.qty=Math.max(1,Math.min(999,item.qty+(action==='increase-qty'?1:-1)));
 const line=button.closest('.item-line');if(line){const input=line.querySelector('.qty-input');if(input)input.value=item.qty;
 const minus=line.querySelector('[data-action="decrease-qty"]'),plus=line.querySelector('[data-action="increase-qty"]');
 if(minus)minus.disabled=item.qty<=1;if(plus)plus.disabled=item.qty>=999;}
 const total=draft.reduce((sum,x)=>sum+(Number(x.qty)||0)*(Number(x.priceCents)||0),0);
 if(el('draft-total'))el('draft-total').textContent=money(total);
 return;}case 'remove-item':if(el('order-form'))el('order-form').dataset.dirty='true';draft.splice(Number(button.dataset.id),1);return renderDraft();case 'refresh':return sync().then(()=>render()).catch(e=>toast(e.message,true));case 'clear-filters':dayFilter='';locationFilter='';orderClientFilter='';closingSearch='';resetPage('pedidos');resetPage('fechamento');return render();case 'export-month-orders':if(allowed('admin','financeiro'))return exportMonthlyText();return;case 'export-month-csv':if(allowed('admin','financeiro'))return exportMonthlyCsv();return;case 'copy-share':{let text=el('share-text').value;navigator.clipboard?.writeText(text).then(()=>toast('Texto copiado.')).catch(()=>{el('share-text').focus();el('share-text').select();toast('Texto selecionado: copie manualmente.')});return}case 'download-share':{let cid=clientGroups()[0]?.cid;let text=el('share-text').value;return download('Extrato_Sabores_das_Divas_'+period+'.txt',text)}case 'open-whatsapp':{let phone=button.dataset.id;if(!/^55\d{10,11}$/.test(phone))return;let text=el('share-text').value;window.open('https://wa.me/'+phone+'?text='+encodeURIComponent(text),'_blank','noopener,noreferrer');return}case 'copy-temp':navigator.clipboard?.writeText(el('temporary-secret').value).then(()=>toast('Senha copiada.')).catch(()=>{el('temporary-secret').select();toast('Senha selecionada: copie manualmente.')});return;case 'export-data':return api('/api/export').then(d=>download('Sabores_Divas_backup_'+today()+'.json',JSON.stringify(d,null,2),'application/json;charset=utf-8')).catch(e=>toast(e.message,true));case 'delete-order':{if(!confirm('Excluir permanentemente este pedido?'))return;return change('/api/orders/'+encodeURIComponent(button.dataset.id),'DELETE',{},'Pedido excluído.')}default:return}}
// Atalho de cadastro de cliente: Ctrl + Alt + N (na aba Clientes).
document.addEventListener('keydown',e=>{
 if((e.ctrlKey||e.metaKey)&&e.altKey&&!e.shiftKey&&e.key.toLowerCase()==='n'&&page==='clientes'&&me&&allowed('admin','operador','financeiro')&&!el('modal-root').querySelector('.modal-back')){
   e.preventDefault();openClient();
 }
});
// Controla as ações dinâmicas sem adicionar JavaScript ao HTML gerado.
document.addEventListener('click',e=>{let b=e.target.closest('[data-nav]');if(b){go(b.dataset.nav);return}if(e.target.closest('[data-close]'))return;b=e.target.closest('[data-action]');if(b){e.preventDefault();pendingModalAction(b.dataset.action,b)}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-list-page]');if(!b)return;e.preventDefault();const key=b.dataset.listPage;const state=listState[key];if(!state)return;state.number=Number(b.dataset.to)||1;render()});
document.addEventListener('change',e=>{const sel=e.target.closest('[data-page-size]');if(!sel)return;listState[sel.dataset.pageSize]={size:Number(sel.value)||20,number:1};render()});
document.addEventListener('keydown',e=>{if(e.key!=='Escape'||!el('modal-root').querySelector('.modal-back'))return;e.preventDefault();e.stopPropagation();if(modalStack.length)modalBack();else requestModalClose()});
document.addEventListener('input',e=>{if(!e.target.matches('[data-draft]'))return;let idx=Number(e.target.dataset.row),i=draft[idx];if(!i)return;switch(e.target.dataset.draft){case 'qty':i.qty=Number(e.target.value);break;case 'name':i.name=e.target.value;break;case 'price':i.priceText=e.target.value;i.priceCents=toCents(e.target.value);break;case 'product':{let p=db.products.find(p=>p.id===e.target.value);if(p){i.productId=p.id;i.name=p.name;i.category=p.category;i.priceCents=p.priceCents}else{i.productId='';i.priceCents=0;i.name=''}break}}if(e.target.dataset.draft==='product'){renderDraft();return}let total=draft.reduce((sum,x)=>sum+(Number(x.qty)||0)*(Number(x.priceCents)||0),0);if(el('draft-total'))el('draft-total').textContent=money(total)});
el('login-form').onsubmit=async e=>{e.preventDefault();let btn=e.submitter;btn.disabled=true;try{let r=await api('/api/login','POST',{identifier:el('login-email').value,password:el('login-password').value,code:el('login-code').value});me=r.user;csrf=r.csrf;el('login-password').value='';el('login-code').value='';await sync();showApp()}catch(err){toast(err.message,true)}finally{btn.disabled=false}};
el('logout').onclick=async()=>{try{await api('/api/logout','POST',{})}catch(_){/* Sessão já expirada. */}me=null;csrf='';db={clients:[],products:[],orders:[]};showLogin();toast('Você saiu do sistema.')};
start();
